### ISSUE TITLE
infinite SetFreqCorrection error

### ISSUE THREAD

**Issue by bradanlane** [cyoung/stratux#106]
setting frequency correct to zero is invalid and returns an error which results in teh sdrConfig code being called repeatedly.

**Comment by bradanlane** [comment]
fix submitted with pull request #107

**Comment by jpoirier** [comment]
Should already be fixed in the gortlsdr library. Setting the freq
correction to zero isn't the problem, the problem is that librtlsdr returns
an erroneous error (-2) when the requested PPM is the same as the currently
configured PPM. The gortlsdr library handles that now.

You really need to read the commit history, and reason out the exact
problem problem before coming to a conclusion.

**Comment by bradanlane** [comment]
Thanks @jpoirier, I did read the commit history but it didn't indicate I needed to do something special to get a build to work. 

Thankfully @cyoung posted a followup comment to let everyone know that we need to do "go get -u all".

I was reading the commits and missed chris's important notice.

**Comment by bradanlane** [comment]
I've closed the pull request.

**Comment by jpoirier** [comment]
Roger. Point taken and I'll be sure and annotate/emphasize/explain when
commits cause side effects to external dependencies.

**Comment by bradanlane** [comment]
thanks. we all back on the same track again. :-)
