### ISSUE TITLE
Setup Continuous Integration Service

### ISSUE THREAD

**Issue by BrantKyser** [cyoung/stratux#15]
TravisCI (travis-ci.com) provides free continuous integration services to open source projects.

It would be beneficial to set this up for the Stratux project, as it ensures builds and tests succeed on commits, pull requests, etc. Setup requires the the repository owner to log into TravisCI and enable support for the repository. Then, a .travis.yml file needs to be added to the repository to specify how to build and test the project. Instructions are at http://docs.travis-ci.com/user/getting-started/ .

@cyoung - if you are interested in getting this setup, log into TravisCI and enable support, and I'll create a pull-request adding the appropriate .travis.yml file.

**Comment by cyoung** [comment]
CircleCI is set up now. The builds fail on there. If someone wants to either 1) fix the circle.yml so that it compiles on their VM, 2) create tests so that it's actually useful, 3) start making changes on the code so that it's fully testable outside of the Pi - then that would be great. If not, will be disabling it in a week or two.
