### ISSUE TITLE
Altitudes showing wrong in Foreflight in latest head build

### ISSUE THREAD

**Issue by braddward** [cyoung/stratux#153]
![img_0253](https://cloud.githubusercontent.com/assets/642781/11919651/3a9eb628-a71e-11e5-8205-77d894666582.PNG)
![img_0252](https://cloud.githubusercontent.com/assets/642781/11919652/3d4a12a0-a71e-11e5-89d4-667e5b85a204.PNG)
Attached are a couple of screenshots showing the issue.  This is from the ground so it's 1090 data.  

I installed earlier production release and it shows up correctly in Foreflight.

**Comment by AvSquirrel** [comment]
Noted in #124.

Traffic messages for altitudes above int16_max (i.e. 32775' or higher) are offset high by 36875' due to integer overflow in traffic.go. Change int16 to int32 to resolve.

alt := int16(math.Max(float64(ti.Alt), float64(-1000.00)))
https://github.com/cyoung/stratux/blob/master/main/traffic.go#L143

**Comment by cyoung** [comment]
Fixed https://github.com/cyoung/stratux/commit/373c0fa9567792e50f1a22721d8712736b3806ad.

This change was made and effective in v0.5b2, give that one a try @braddward.

**Comment by braddward** [comment]
Confirmed that this is resolved.  Thanks!
