### ISSUE TITLE
AHRS shows inverted on Wingx at 0 AGL or lower

### ISSUE THREAD

**Issue by laluzdiy** [cyoung/stratux#165]
I noticed the AHRS is inverted (ground and sky is reversed) when running a simulation on Wingx if the adjusted GPS altitude is 0 or below ground level.  Would not normally be a problem unless the adjusted or corrected altitude is too low.  I haven't been able to get AHRS to work in FF so unable to test it there.  I don't think stratux code does anything with the roll code in connection with altitude so this may be something specific to Wingx.
I'm using stratux v0.5b2, Wingx Pro7 version 8.6.2.1 on iPad, with GPS data from Dual XGPS150.

![img_0007](https://cloud.githubusercontent.com/assets/16065147/12007818/68e140dc-abd3-11e5-93a7-3aaff11397b4.PNG)

**Comment by HiltonG** [comment]
Hi,

The performance of the RY835AI + Stratux is really good, responsive etc (good work Chris).  What you're seeing here is not an issue with Stratux at all.  WingX Pro7 does not check for 0 AGL so this is your being underground and the earth's surface above you.  Something we need to fix.  It is easy to verify this, simply slide your finger down the altitude slider on the right to change altitude and you will magically popup above the earth; i.e. nothing wrong with Stratux or the communication (and hence data stream) between Stratux and WingX Pro7 and nothing being inverted.  The easiest way to solve the problem is to tap on the altitude at the very top, you will see that Altitude Calibration popdown, just add a few feet (and/or correctly calibrate the altitude).

Hilton

**Comment by laluzdiy** [comment]
Thanks for responding,
I later realized I could duplicate this without even connecting to stratux so it had to be specific to app.
