### ISSUE TITLE
v0.5b4 (and earlier releases) - aircraft > FL 18 on FF depicting 978UAT not 1080ES

### ISSUE THREAD

**Issue by gitmoregrits** [cyoung/stratux#181]
Fantastic project -thanks to cyoung and the other contributors.  Amazing work you're driving.

Using ForeFlight 7.5.1, dual SDRs, etc.  I've noticed this on earlier builds as well...

Targets at flight levels above FL18 all report 978/UAT in the FF UI when I tap on the target.  Should I be seeing these as 1090ES?  From the browser and connecting to the RPI under status I see, for example, lots of 1090ES messages being received but no 978/UAT but yet the aircraft on FF are painting 978UAT.

**Comment by cyoung** [comment]
Thanks for posting, that's a known issue with FF. If you want to see what source traffic is coming from, enable "Traffic Markings" in the web interface. "u" for UAT and "e" for 1090ES. I'll close this now because it's more of an aesthetic issue and we'll work on it eventually, but feel free to post to the issue further information.
