### ISSUE TITLE
Skydemon

### ISSUE THREAD

**Issue by GrimShadow** [cyoung/stratux#475]
Hey Cyoung,

Is it possible to get stratux working on Skydemon? I have changed the default of stratux to 192.168.1.1 as skydemon looks at that address for GPS/Traffic data. The only thing I need to figure out is how to generate a Air Connect key to allow communications to happen.

Any advice would be greatly appreciated

**Comment by cyoung** [comment]
Hi @GrimShadow,

See here: http://forums.skydemon.aero/Topic14379.aspx
And here: #218.

Since they don't seem to have many users (or maybe this is the first I've really heard of it), we'll defer decision on this since we are looking at FLARM output anyway. If SkyDemon wants to add support or you want to encourage them to do so, have them see the integration guide: 
https://github.com/cyoung/stratux/blob/master/notes/app-vendor-integration.md


Thanks,
Chris
